/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mock_acados_solver_impl_dae_hess_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {2, 1, 1};
static const casadi_int casadi_s5[18] = 
  {9, 9, 0, 0, 3, 3, 5, 5,
  5, 5, 5, 6, 1, 3, 8, 1,
  3, 1};

/* mock_acados_solver_impl_dae_hess:(i0[4],i1[4],i2,i3[0],i4[4],i5[],i6[2])->(o0[9x9,6nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39;
  a00=arg[0]? arg[0][1] : 0;
  a01=cos(a00);
  a02=9.8100000000000005e+00;
  a03=arg[6]? arg[6][0] : 0;
  a04=arg[6]? arg[6][1] : 0;
  a03=(a03+a04);
  a05=(a02*a03);
  a06=arg[4]? arg[4][3] : 0;
  a07=8.0000000000000004e-01;
  a08=(a04*a01);
  a09=(a08*a01);
  a03=(a03-a09);
  a09=(a07*a03);
  a10=(a06/a09);
  a11=(a10/a09);
  a00=sin(a00);
  a12=(a04*a00);
  a13=(a01*a12);
  a14=(a08*a00);
  a13=(a13+a14);
  a14=(a07*a13);
  a11=(a11*a14);
  a15=(a05*a11);
  a16=arg[0]? arg[0][3] : 0;
  a17=(a16*a10);
  a18=(a16*a17);
  a19=(a07*a04);
  a20=(a19*a00);
  a21=(a18*a20);
  a22=(a19*a01);
  a23=(a16*a11);
  a24=(a16*a23);
  a25=(a22*a24);
  a21=(a21+a25);
  a15=(a15-a21);
  a21=arg[4]? arg[4][2] : 0;
  a25=(a21/a03);
  a26=(a25/a03);
  a26=(a26*a13);
  a27=(a16*a26);
  a28=(a16*a27);
  a28=(a19*a28);
  a15=(a15-a28);
  a02=(a02*a04);
  a28=(a02*a00);
  a29=(a25*a28);
  a30=(a02*a01);
  a31=(a30*a26);
  a29=(a29+a31);
  a15=(a15+a29);
  a15=(a01*a15);
  a29=(a22*a18);
  a31=(a05*a10);
  a29=(a29-a31);
  a31=(a16*a25);
  a32=(a16*a31);
  a32=(a19*a32);
  a29=(a29+a32);
  a32=(a30*a25);
  a29=(a29-a32);
  a29=(a29*a00);
  a15=(a15-a29);
  a29=(a00*a18);
  a29=(a19*a29);
  a32=arg[2]? arg[2][0] : 0;
  a33=(a32*a10);
  a29=(a29-a33);
  a33=(a32*a01);
  a34=(a22*a00);
  a35=(a34*a16);
  a36=(a35*a16);
  a33=(a33-a36);
  a36=(a05*a00);
  a33=(a33+a36);
  a33=(a33/a09);
  a33=(a33/a09);
  a36=(a33*a06);
  a36=(a07*a36);
  a37=(a30*a00);
  a38=(a20*a16);
  a39=(a38*a16);
  a37=(a37-a39);
  a37=(a37+a32);
  a37=(a37/a03);
  a37=(a37/a03);
  a39=(a37*a21);
  a36=(a36+a39);
  a39=(a08*a36);
  a29=(a29-a39);
  a39=(a01*a36);
  a39=(a04*a39);
  a29=(a29-a39);
  a39=(a00*a25);
  a39=(a02*a39);
  a29=(a29-a39);
  a29=(a29*a01);
  a18=(a18*a01);
  a24=(a00*a24);
  a18=(a18-a24);
  a19=(a19*a18);
  a18=(a32*a11);
  a19=(a19+a18);
  a05=(a05*a01);
  a32=(a32*a00);
  a18=(a22*a01);
  a24=(a00*a20);
  a18=(a18-a24);
  a24=(a16*a18);
  a39=(a16*a24);
  a32=(a32+a39);
  a05=(a05-a32);
  a05=(a05/a09);
  a32=(a33*a14);
  a05=(a05-a32);
  a05=(a05/a09);
  a33=(a33/a09);
  a33=(a33*a14);
  a05=(a05-a33);
  a06=(a06*a05);
  a07=(a07*a06);
  a30=(a30*a01);
  a28=(a00*a28);
  a30=(a30-a28);
  a28=(a16*a22);
  a16=(a16*a28);
  a30=(a30-a16);
  a30=(a30/a03);
  a16=(a37*a13);
  a30=(a30-a16);
  a30=(a30/a03);
  a37=(a37/a03);
  a37=(a37*a13);
  a30=(a30-a37);
  a21=(a21*a30);
  a07=(a07+a21);
  a08=(a08*a07);
  a12=(a36*a12);
  a08=(a08-a12);
  a19=(a19-a08);
  a07=(a01*a07);
  a36=(a36*a00);
  a07=(a07-a36);
  a04=(a04*a07);
  a19=(a19-a04);
  a04=(a25*a01);
  a07=(a00*a26);
  a04=(a04-a07);
  a02=(a02*a04);
  a19=(a19-a02);
  a19=(a00*a19);
  a29=(a29+a19);
  a15=(a15-a29);
  if (res[0]!=0) res[0][0]=a15;
  a24=(a10*a24);
  a35=(a35*a11);
  a24=(a24-a35);
  a17=(a17*a18);
  a23=(a34*a23);
  a17=(a17-a23);
  a24=(a24+a17);
  a28=(a25*a28);
  a38=(a38*a26);
  a28=(a28-a38);
  a24=(a24+a28);
  a31=(a31*a22);
  a27=(a20*a27);
  a31=(a31-a27);
  a24=(a24+a31);
  if (res[0]!=0) res[0][1]=a24;
  a00=(a10*a00);
  a01=(a01*a11);
  a00=(a00+a01);
  a00=(a00+a26);
  if (res[0]!=0) res[0][2]=a00;
  if (res[0]!=0) res[0][3]=a24;
  a24=(a10*a34);
  a34=(a34*a10);
  a24=(a24+a34);
  a34=(a25*a20);
  a24=(a24+a34);
  a20=(a20*a25);
  a24=(a24+a20);
  if (res[0]!=0) res[0][4]=a24;
  if (res[0]!=0) res[0][5]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int mock_acados_solver_impl_dae_hess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mock_acados_solver_impl_dae_hess_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mock_acados_solver_impl_dae_hess_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mock_acados_solver_impl_dae_hess_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mock_acados_solver_impl_dae_hess_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mock_acados_solver_impl_dae_hess_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mock_acados_solver_impl_dae_hess_incref(void) {
}

CASADI_SYMBOL_EXPORT void mock_acados_solver_impl_dae_hess_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mock_acados_solver_impl_dae_hess_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int mock_acados_solver_impl_dae_hess_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real mock_acados_solver_impl_dae_hess_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mock_acados_solver_impl_dae_hess_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    case 6: return "i6";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mock_acados_solver_impl_dae_hess_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mock_acados_solver_impl_dae_hess_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s0;
    case 5: return casadi_s3;
    case 6: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mock_acados_solver_impl_dae_hess_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mock_acados_solver_impl_dae_hess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int mock_acados_solver_impl_dae_hess_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
