/* This file was automatically generated by CasADi 3.7.0.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) mock_acados_solver_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {4, 1, 1};
static const casadi_int casadi_s1[3] = {1, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[3] = {2, 1, 1};
static const casadi_int casadi_s5[13] = 
  {4, 4, 0, 0, 2, 3, 6, 2,
  3, 0, 1, 2, 3};
static const casadi_int casadi_s6[11] = 
  {4, 4, 0, 1, 2, 3, 4, 0,
  1, 2, 3};
static const casadi_int casadi_s7[6] = {4, 1, 0, 2, 2, 3};
static const casadi_int casadi_s8[3] = {4, 0, 1};

/* mock_acados_solver_impl_dae_jac_x_xdot_u_z:(i0[4],i1[4],i2,i3[0],i4[],i5[2])->(o0[4x4,6nz],o1[4x4,4nz],o2[4x1,2nz],o3[4x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14;
  a00=9.8100000000000005e+00;
  a01=arg[5]? arg[5][1] : 0;
  a02=(a00*a01);
  a03=arg[0]? arg[0][1] : 0;
  a04=cos(a03);
  a05=(a02*a04);
  a06=(a05*a04);
  a03=sin(a03);
  a02=(a02*a03);
  a02=(a03*a02);
  a06=(a06-a02);
  a02=arg[0]? arg[0][3] : 0;
  a07=8.0000000000000004e-01;
  a08=(a07*a01);
  a09=(a08*a04);
  a10=(a02*a09);
  a10=(a02*a10);
  a06=(a06-a10);
  a10=arg[5]? arg[5][0] : 0;
  a10=(a10+a01);
  a11=(a01*a04);
  a12=(a11*a04);
  a12=(a10-a12);
  a06=(a06/a12);
  a05=(a05*a03);
  a08=(a08*a03);
  a13=(a08*a02);
  a14=(a13*a02);
  a05=(a05-a14);
  a14=arg[2]? arg[2][0] : 0;
  a05=(a05+a14);
  a05=(a05/a12);
  a05=(a05/a12);
  a01=(a01*a03);
  a01=(a04*a01);
  a11=(a11*a03);
  a01=(a01+a11);
  a05=(a05*a01);
  a06=(a06-a05);
  a06=(-a06);
  if (res[0]!=0) res[0][0]=a06;
  a00=(a00*a10);
  a10=(a00*a04);
  a06=(a14*a03);
  a05=(a09*a04);
  a11=(a03*a08);
  a05=(a05-a11);
  a05=(a02*a05);
  a05=(a02*a05);
  a06=(a06+a05);
  a10=(a10-a06);
  a06=(a07*a12);
  a10=(a10/a06);
  a14=(a14*a04);
  a09=(a09*a03);
  a05=(a09*a02);
  a11=(a05*a02);
  a14=(a14-a11);
  a00=(a00*a03);
  a14=(a14+a00);
  a14=(a14/a06);
  a14=(a14/a06);
  a07=(a07*a01);
  a14=(a14*a07);
  a10=(a10-a14);
  a10=(-a10);
  if (res[0]!=0) res[0][1]=a10;
  a10=-1.;
  if (res[0]!=0) res[0][2]=a10;
  if (res[0]!=0) res[0][3]=a10;
  a08=(a02*a08);
  a08=(a08+a13);
  a08=(a08/a12);
  if (res[0]!=0) res[0][4]=a08;
  a02=(a02*a09);
  a02=(a02+a05);
  a02=(a02/a06);
  if (res[0]!=0) res[0][5]=a02;
  a02=1.;
  if (res[1]!=0) res[1][0]=a02;
  if (res[1]!=0) res[1][1]=a02;
  if (res[1]!=0) res[1][2]=a02;
  if (res[1]!=0) res[1][3]=a02;
  a12=(1./a12);
  a12=(-a12);
  if (res[2]!=0) res[2][0]=a12;
  a04=(a04/a06);
  a04=(-a04);
  if (res[2]!=0) res[2][1]=a04;
  return 0;
}

CASADI_SYMBOL_EXPORT int mock_acados_solver_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int mock_acados_solver_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int mock_acados_solver_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mock_acados_solver_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int mock_acados_solver_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void mock_acados_solver_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void mock_acados_solver_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void mock_acados_solver_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int mock_acados_solver_impl_dae_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int mock_acados_solver_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real mock_acados_solver_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mock_acados_solver_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* mock_acados_solver_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mock_acados_solver_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* mock_acados_solver_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s7;
    case 3: return casadi_s8;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int mock_acados_solver_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int mock_acados_solver_impl_dae_jac_x_xdot_u_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
